<a href="https://colab.research.google.com/github/tmedeirosb/tsi-ad-2025/blob/main/MODULO_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# exibir todas as colunas
pd.set_option('display.max_columns', None)

url = "https://raw.githubusercontent.com/tmedeirosb/tsi-ad-2025/refs/heads/main/dados/dados_workflow_ivan.csv"
df = pd.read_csv(url)

display(df.head())

,LnguaPortuguesaeLiteraturaI90H,LnguaPortuguesaeLiteraturaI90H_dependencia,LnguaPortuguesaeLiteraturaI90H_freq,MatemticaI120H,MatemticaI120H_dependencia,MatemticaI120H_freq,aluno_exclusivo_rede_publica,descricao,descricao_area_residencial,descricao_companhia_domiciliar,descricao_estado_civil,descricao_historico,descricao_imovel,descricao_mae_escolaridade,descricao_pai_escolaridade,descricao_raca,descricao_responsavel_escolaridade,descricao_responsavel_financeiro,descricao_trabalho,id,idade,pessoa_fisica__sexo,possui_necessidade_especial,qnt_pc,qtd_pessoas_domicilio,sigla,tempo_entre_conclusao_ingresso,qnt_salarios,artificial,classe,conceito,conceito_freq,acompanhamento
0,68.0,0,100.0,66.0,0,100.0,False,Matriculado,Urbana,Mãe,Solteiro(a),Técnico de Nivel Médio em Informática,Alugado,Ensino fundamental incompleto,Ensino fundamental incompleto,Branca,Ensino fundamental incompleto,Mãe,Não informado,457884597605,15,F,False,0,2,LAJ,1,1,0,1,B,A,0
1,73.0,1,100.0,36.0,1,91.0,False,Cancelado,Urbana,Mãe,Solteiro(a),Técnico de Nível Médio em Meio Ambiente,Alugado,Ensino fundamental incompleto,Ensino fundamental incompleto,Parda,Ensino fundamental incompleto,Mãe,Não informado,458436647741,17,M,False,1,2,SPP,2,1,1,0,R,R,0
2,61.0,0,100.0,60.0,0,100.0,False,Matriculado,Urbana,Pais,Solteiro(a),Técnico de Nivel Médio em Informática,Alugado,Ensino médio completo,Ensino médio completo,Parda,Ensino médio completo,Mãe,Não informado,464029640533,15,M,True,0,5,CANG,2,2,0,1,B,A,0
3,NaN,-1,NaN,NaN,-1,NaN,False,Matriculado,Urbana,Pais,Solteiro(a),Técnico de Nível Médio em Mecânica,Alugado,Alfabetizado,Não estudou,Parda,Ensino fundamental incompleto,Mãe,Não está trabalhando,556372572373,16,F,False,1,5,MO,3,2,0,1,S,S,0
4,69.0,0,100.0,63.0,0,100.0,False,Matriculado,Urbana,Mãe,Solteiro(a),Técnico de Nivel Médio Informática,Alugado,Ensino fundamental incompleto,Ensino fundamental incompleto,Preta,Ensino fundamental incompleto,Mãe,Não está trabalhando,457614148801,15,F,False,0,3,PAR,1,1,0,1,R,A,2

In [4]:
df_sel = df[['LnguaPortuguesaeLiteraturaI90H', 'MatemticaI120H', 'descricao_responsavel_escolaridade', 'qnt_salarios', 'descricao_raca', 'idade', 'pessoa_fisica__sexo', 'classe']]
df_sel

,LnguaPortuguesaeLiteraturaI90H,MatemticaI120H,descricao_responsavel_escolaridade,qnt_salarios,descricao_raca,idade,pessoa_fisica__sexo,classe
0,68.0,66.0,Ensino fundamental incompleto,1,Branca,15,F,1
1,73.0,36.0,Ensino fundamental incompleto,1,Parda,17,M,0
2,61.0,60.0,Ensino médio completo,2,Parda,15,M,1
3,NaN,NaN,Ensino fundamental incompleto,2,Parda,16,F,1
4,69.0,63.0,Ensino fundamental incompleto,1,Preta,15,F,1
...,...,...,...,...,...,...,...,...
8903,29.0,11.0,Ensino fundamental incompleto,1,Amarela,15,M,0
8904,86.0,71.0,Ensino fundamental incompleto,1,Branca,15,F,1
8905,61.0,67.0,Ensino fundamental incompleto,1,Parda,15,F,1
8906,93.0,78.0,Ensino fundamental incompleto,1,Parda,14,F,1
8907,81.0,63.0,Ensino fundamental incompleto,1,Branca,15,M,1